appName: currencyservice
appImage: gcr.io/google-samples/microservices-demo/currencyservice
appVersion: v0.6.0
appReplicas: 2
containerPort: 7000
containerEnvVars:
- name: PORT
  value: "7000"
- name: DISABLE_PROFILER
  value: "1"
appLimCPU: 300m

servicePort: 7000