appName: emailservice
appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.6.0
appReplicas: 2
containerEnvVars:
- name: PORT
  value: "8080"
- name: DISABLE_PROFILER
  value: "1"
appReqCPU: 100m
appReqMemory: 64Mi
appLimCPU: 200m
appLimMemory: 128Mi
