appName: recommendationservice
appImage: gcr.io/google-samples/microservices-demo/recommendationservice
appVersion: v0.6.0
appReplicas: 2
containerEnvVars:
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: DISABLE_PROFILER
  value: "1"
appReqMemory: 220Mi
appLimMemory: 450Mi

servicePort: 8080